npmRegistries:
  "https://packages.atlassian.com/artifactory/artifactory/api/npm/npm-remote":
    npmAlwaysAuth: false

npmScopes:
  atlassian:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://packages.atlassian.com/artifactory/artifactory/api/npm/atlassian-npm"
    npmRegistryServer: "https://packages.atlassian.com/artifactory/artifactory/api/npm/atlassian-npm"
  atlassiansox:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://packages.atlassian.com/artifactory/artifactory/api/npm/atlassian-npm-sox"
    npmRegistryServer: "https://packages.atlassian.com/artifactory/artifactory/api/npm/atlassian-npm-sox"
